spring:
  thymeleaf:
    cache: false
#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:file:/tmp/bookmark
#    username: sa
#    password:
  jpa:
    database: H2
    hibernate:
      ddl-auto: update
  resources:
    cache-period: #{60 * 60 * 24 * 3}
security:
  basic:
    enabled: false
